Check branch
theheadmen/goDipl2 pull request #1
Opened 2024-02-15 08:30 UTC by theheadmen

2024-02-15 11:41 UTC, bambruysk requested changes
Начать нужно с архитектуры приложения

2024-02-15 11:41 UTC, bambruysk commented on cmd/gophermart/db.go
> +package main
Все разложить по пакетам и слоям

2024-02-15 11:41 UTC, bambruysk commented on cmd/gophermart/main.go
> +	r.HandleFunc("/api/user/register", ls.RegisterUserHandler).Methods("POST")
почему хендлеры это методы приложения?

2024-02-15 11:41 UTC, bambruysk commented on cmd/gophermart/models.go
> +type User struct {
gorm должен использоваться только для локальных моделей репозитория

2024-02-15 11:41 UTC, bambruysk commented on cmd/gophermart/models.go
> +	Balance  float64 `gorm:"default:0"`
Баланс нельзя использовать с плавающей точкой

2024-02-15 11:41 UTC, bambruysk commented on cmd/gophermart/db_test.go
> +	}()
оно наверное должно как-то реагировать на получение данных из канала

2024-02-15 11:41 UTC, bambruysk commented on cmd/gophermart/db.go
> +package main
в cmd должен быть только пакет мейн содержащий только инициализацию архитектуры выского уровня

2024-02-15 11:41 UTC, bambruysk commented on cmd/gophermart/main.go
> +	// Горутина, которая ждет данных из канала
а кто их туда кладет?

2024-02-15 12:24 UTC, theheadmen commented on cmd/gophermart/models.go
> +type User struct {
@bambruysk не совсем понимаю что значит "локальные модели репозитория".
А они разве все не локальные в рамках проекта?
Или какие из них тогда локальные, а какие нет?

2024-02-15 12:25 UTC, theheadmen commented on cmd/gophermart/models.go
> +	Balance  float64 `gorm:"default:0"`
@bambruysk так ведь даже в примере указано, что баланс не int

в хендлере для чекания баланса пользователя
  200 OK HTTP/1.1
  Content-Type: application/json
  ...
  
  {
      "current": 500.5,
      "withdrawn": 42
  }

2024-02-15 12:27 UTC, theheadmen commented on cmd/gophermart/db_test.go
> +	}()
@bambruysk да, но так как я тестирую свой сервис - что мне сюда стоить поместить?
Какую-то заглушку или просто руками проставлять желаемое количество баллов?

2024-02-15 12:28 UTC, theheadmen commented on cmd/gophermart/main.go
> +	// Горутина, которая ждет данных из канала
Хендлер который принимает Orders

2024-02-15 12:29 UTC, theheadmen commented on cmd/gophermart/main.go
> +	r.HandleFunc("/api/user/register", ls.RegisterUserHandler).Methods("POST")
В смысле почему они настраиваются в main.go?

2024-02-18 14:02 UTC, bambruysk requested changes
Надо доработать. Особенно в части транзакций и вынесения логики работы в слой бизнес-логики

2024-02-18 14:02 UTC, bambruysk commented on internal/server/server_utils.go
> +func MakeGorutineToCheckOrdersByTimer(ctx context.Context, ls *ServerSystem) {
луччше бы это было методом ServerSystem

2024-02-18 14:02 UTC, bambruysk commented on internal/server/server_utils.go
> +func MakeGorutineToCheckOrder(ctx context.Context, ls *ServerSystem) {
луччше бы это было методом ServerSystem

2024-02-18 14:02 UTC, bambruysk commented on internal/server/server_utils.go
> +				return
Если выйти по отмене контекста, то кто-то должен довычитать оставшиеся там данные

2024-02-18 14:02 UTC, bambruysk commented on internal/server/server_utils.go
> +func fetchOrderInfo(db *dbconnector.DBConnector, ord *models.Order, baseURL string, ctx context.Context) error {
лучше бы это было методом db - так понятнее, и во вторых проще работать с зависимостями, 

Контекст всегда должен передавать первым аргументом

2024-02-18 14:02 UTC, bambruysk commented on internal/server/server_utils.go
> +	defer resp.Body.Close()
лучше воспользоваться resty 
Ну или сложить это в отдельный метод типа GetFromAccrual

2024-02-18 14:02 UTC, bambruysk commented on internal/server/server_utils.go
> +		log.Printf("User %d now have %f\n", ord.UserID, user.Balance)
Здесь возможна гонка данных между запросами

2024-02-18 14:02 UTC, bambruysk commented on internal/server/server_utils.go
> +	return nil
в чем разница, если ответ один?

2024-02-18 14:02 UTC, bambruysk commented on internal/server/server_utils.go
> +	}
Это как-то обрабатывается где-то?

2024-02-18 14:02 UTC, bambruysk commented on internal/dbconnector/dbconnector.go
> +func (dbConnector *DBConnector) GetUserByEmail(email string, user *models.User, ctx context.Context) error {
контекст передается первым

2024-02-18 14:02 UTC, bambruysk commented on internal/dbconnector/dbconnector.go
> +func (dbConnector *DBConnector) GetOrderByNumber(orderNumber string, existingOrder *models.Order, ctx context.Context) error {
контекст передается первым

2024-02-18 14:02 UTC, bambruysk commented on internal/dbconnector/dbconnector.go
> +
контекст передается первым

2024-02-18 14:02 UTC, bambruysk commented on internal/models/models.go
> +}
Эти модели должны быть локальными для слоя хранилища, так как иначе мы имеем зависимость от gorm в моделях

2024-02-18 14:02 UTC, bambruysk commented on internal/server/server.go
> +	var existingOrder models.Order
Лучше просто сделать ограничение в базе на уникальность заказа, иначе заказ может быть создан в параллельном запросе

2024-02-18 14:02 UTC, bambruysk commented on internal/server/server.go
> +	ls.Datachan <- order
здесь потенциально можно заблокироваться на долго. Вообще не хорошо когда хендлеры используют асинхронный код, Лучше бы это все вынести на слой бизнес-логики

2024-02-18 14:02 UTC, bambruysk commented on internal/server/server.go
> +	}
Это можно было бы вынести в отдельный метод и/или middleware

2024-02-18 14:02 UTC, bambruysk commented on internal/server/server.go
> +	json.NewEncoder(w).Encode(orderResponses)
статус не указан

2024-02-18 14:02 UTC, bambruysk commented on internal/server/server.go
> +		log.Println("but user don't have enough money")
логгер лучше бы использовать промышленный

2024-02-18 14:02 UTC, bambruysk commented on internal/server/server.go
> +	if user.Balance < withdrawRequest.Sum {
к этому моменту информация в базе может уже измениться. Например мы одновременно послали два запроса на списание - могут сработать оба ( но денег на всех не хватит)

2024-02-18 14:02 UTC, bambruysk commented on internal/server/server.go
> +		return
а зачем у нас и заказ и и списание сохраняются?

2024-02-18 14:02 UTC, bambruysk commented on internal/server/server.go
> +	w.WriteHeader(http.StatusOK)
В этом хендлере слишком много всего и бизнеслогика, и походы в базу и длинная транзакция. Лучше бы перенести это все в отдельный слой

2024-02-19 06:13 UTC, theheadmen commented on internal/server/server_utils.go
> +	}
Нет - просто в этот заход мы не получили данных и ждем когда по таймеру обратимся заново

2024-02-19 06:16 UTC, theheadmen commented on internal/server/server.go
> +		return
Так ведь это две разные сущности.
И хранить и удобно, и отображать потом при запросах

2024-02-19 06:20 UTC, theheadmen commented on internal/server/server_utils.go
> +				return
Там - в смысле в канале?

2024-03-03 09:12 UTC, bambruysk requested changes
Нужно порефачить и поправить слишкеом длинные и многоумеющие хендлеры

2024-03-03 09:12 UTC, bambruysk commented on internal/server/server.go
> +	if user.Balance < withdrawRequest.Sum {
не исправлено

2024-03-03 09:12 UTC, bambruysk commented on internal/server/server.go
> +	w.WriteHeader(http.StatusOK)
не исправлено

2024-03-04 17:44 UTC, bambruysk requested changes
Нужно порефачить

2024-03-04 17:44 UTC, bambruysk commented on internal/service/logic.go
> +func LoadOrderLogic(ctx context.Context, orderNumber string, storage Storage, w http.ResponseWriter, user dbconnector.User) error {
зачем сюда затесался http.ResponseWriter?  функция может просто возвращать ошибку, а на ее основе хендлер придумывает что отвечать

2024-03-04 17:44 UTC, bambruysk commented on internal/service/logic.go
> +	err := storage.GetOrderByNumber(ctx, orderNumber, &existingOrder)
Это не Си. Заказ надо возвращать из хранилища как значение, а не передавать по указателю.

2024-03-04 17:44 UTC, bambruysk commented on internal/service/logic.go
> +	if err == nil {
может быть if err **!=** nil?

2024-03-04 17:44 UTC, bambruysk commented on internal/service/logic.go
> +	err := storage.WithdrawalTransaction(ctx, &order, &withdrawal, &user, userEmail, withdrawRequest.Sum, fundError)
зачем передавать ошибку, а потом возвращать ее? 
В Go принято создать заранее подоговленный  известный сервису набор ошибок и возвращать их

типа var ErrInsuffisientFunds и вернуть ее. А тут сравнить.

2024-03-04 17:44 UTC, bambruysk commented on internal/service/logic.go
> +func LoginUserLogic(ctx context.Context, storage Storage, reqUser dbconnector.User) (int /*responce code*/, error) {
Не очень удобно в каждую функцию передавать аргумент, один и тот же. Лучше связать их в структуру и сделать эти функции методом этой структуры

2024-03-04 17:44 UTC, bambruysk commented on internal/service/logic.go
> +	err := storage.GetUserByEmail(ctx, reqUser.Email, &user)
Лучше просто вернуть из этой функции пользователя

2024-03-04 17:44 UTC, bambruysk commented on internal/dbconnector/dbconnector.go
> +	result = tx.Create(&order).WithContext(ctx)
а зачем и заказ создавть и списание? У нас же это вроде бы разные сущности

2024-03-05 14:17 UTC, theheadmen commented on internal/dbconnector/dbconnector.go
> +	result = tx.Create(&order).WithContext(ctx)
Да, но мы создать то должны их одновременно
Проверили деньги -> списали -> записали списание -> сделали заказ

2024-03-08 07:18 UTC, bambruysk approved these changes
Принято

2024-03-11 07:19 UTC, merged